"""add new column

Revision ID: 20e5e077ceb6
Revises: d2e89db0cac9
Create Date: 2026-01-06 11:56:51.276115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e5e077ceb6'
down_revision: Union[str, Sequence[str], None] = 'd2e89db0cac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('estimated_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_orders_estimated_time'), 'orders', ['estimated_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_estimated_time'), table_name='orders')
    op.drop_column('orders', 'estimated_time')
    # ### end Alembic commands ###
