"""add new column into order

Revision ID: c424528c8b3b
Revises: 20e5e077ceb6
Create Date: 2026-01-20 17:18:35.235298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c424528c8b3b'
down_revision: Union[str, Sequence[str], None] = '20e5e077ceb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_ready_in', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_orders_order_ready_in'), 'orders', ['order_ready_in'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_ready_in'), table_name='orders')
    op.drop_column('orders', 'order_ready_in')
    # ### end Alembic commands ###
